version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: playup-postgres
    restart: always
    environment:
      POSTGRES_DB: playup_db
      POSTGRES_USER: playup_user
      POSTGRES_PASSWORD: playup_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:

